apiVersion: v1
kind: Namespace
metadata:
    name: project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: jenkinscontainer
        image: senthilkumar03/jenkinrepo:75
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: project
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
